Wisconsin county-level data
covid-projections/can-scrapers pull request #13
Opened 2020-12-04 22:01 UTC by MattSidor

County-level scraper for Wisconsin data.

Additional state-level scraper that includes detailed demographic breakdowns will be completed in another pull request.

2020-12-08 00:37 UTC, cc7768 requested changes
Overall this looks great! Thanks for putting together it together.

The one change I explicitly added was including an import in the `can_tools/scrapers/official/__init__.py` file (I added this to get it working while I reviewed the PR).

I think you said that you were going to do the demographic cases/deaths in a separate PR so I will keep an eye out for that.

2020-12-08 20:11 UTC, MattSidor commented on can_tools/scrapers/official/WI/wi_state.py
> +        }
Yes, you're right -- "Antigen and antibody test results are not included in this file."  Thank you.

2020-12-08 20:15 UTC, MattSidor commented on can_tools/scrapers/official/WI/wi_state.py
> +                dt=self._retrieve_dt("US/Eastern"), vintage=self._retrieve_vintage()
Thanks. For states spread across multiple time zones -- e.g. counties in the Florida panhandle; some counties in the northwestern/southwestern corners of Indiana -- should we just use the state's "main" timezone for all counties?

2020-12-08 21:56 UTC, cc7768 commented on can_tools/scrapers/official/WI/wi_state.py
> +                dt=self._retrieve_dt("US/Eastern"), vintage=self._retrieve_vintage()
That's a good question -- I'll propose that we use the timezone of the state capital (so for FL that would be Jacksonville which is Eastern).

I'm open to other thoughts on this though

Ping @sglyon

2020-12-09 00:49 UTC, sglyon commented on can_tools/scrapers/official/WI/wi_state.py
> +                dt=self._retrieve_dt("US/Eastern"), vintage=self._retrieve_vintage()
That sounds great. Good question and answer

2020-12-09 02:25 UTC, sglyon commented
Hey green light from CI :tada:

2020-12-09 06:13 UTC, cc7768 approved these changes

2020-12-09 06:13 UTC, merged