add Nebraska vaccine demographic scrapers
covid-projections/can-scrapers pull request #160
Opened 2021-03-14 19:57 UTC by smcclure17

Dashboard Source: https://experience.arcgis.com/experience/ece0db09da4d4ca68252c3967aa1e9dd/page/page_1/

Add scrapers to track `total_vaccine_initiated`, `total_vaccine_completed`, and `total_vaccine_doses_administered` by race, sex, age, and ethnicity.

**One question/note:** Does the `total_vaccine_initiated`  category include people/doses from single-dose vaccines (such as J&J)?

### Variables Tracked:
- `attributes.TotalFirstDose`: 
     - _description_: "Includes all 1st dose and single dose vaccines administered for Nebraska residents;"
     - _tracked as_: `total_vaccine_initiated`
- `attributes.TotalCompletedVac`: 
     - _description_: No description is given, but it appears to include completed second dose series _and_ completed single dose
     - _tracked as_: `total_vaccine_completed`
- `attributes.TotalDoses`: 
     - _description_: "The number of vaccinations given at a Nebraska location"
     - _tracked as_: `total_vaccine_doses_administered`

### Other Variables Supplied:
Other variables are supplied and could be tracked, but are not in our current schema. Including:
- `attributes.TotalSingleDose`: 
     - _description_: doses of single-shot series vaccines
- `attributes.TotalSecondDose`: 
     - _description_: total number of second dose vaccinations (_not_ including single-dose completions)

2021-04-05 12:48 UTC, tlyon3 commented
@smcclure17, could you resolve merge conflicts and request a review?

2021-04-06 14:02 UTC, tlyon3 requested changes

2021-04-06 14:02 UTC, tlyon3 commented on can_tools/scrapers/official/NE/ne_vaccines.py
> +class NebraskaVaccineSex(StateDashboard):
Unable to request data. Getting some http errors

2021-04-06 14:02 UTC, tlyon3 commented on can_tools/scrapers/official/NE/ne_vaccines.py
> +class NebraskaVaccineRace(NebraskaVaccineSex):
HTTP errors as well

2021-04-06 14:02 UTC, tlyon3 commented on can_tools/scrapers/official/NE/ne_vaccines.py
> +class NebraskaVaccineEthnicity(NebraskaVaccineSex):
HTTP errors as well

2021-04-06 14:48 UTC, sglyon approved these changes
@tlyon3 these all worked for me, I think the problem might be with access from foreign country?

I'm going to merge

2021-04-06 14:48 UTC, merged

2021-04-06 15:24 UTC, tlyon3 commented
Ok I have had that problem with some dashboards before. I've been able to access them by connecting to a VPN, but it didn't work this time. Sounds like it's just a problem with that