Florida demographis data
covid-projections/can-scrapers pull request #218
Opened 2021-04-04 18:41 UTC by mehanig

This PR reads data from http://ww11.doh.state.fl.us/comm/_partners/covid19_report_archive/vaccine-county/vaccine_county_report_latest.pdf

And tries to create one dataframe with merged values, but I am not sure I understand the final schema should look like

Dataframe with only age data looks like this (dfs_demographics variable at line 48):
![image](https://user-images.githubusercontent.com/5033274/113518294-b2ed0980-9585-11eb-8f55-3737003020eb.png)

Can someone give me advice how this should be merged into final Dataframe.
I commened the code which supposed to do something similar, but it doesnt work and I want to have a feedback before I dig deeper into it

2021-04-08 00:10 UTC, mehanig commented
@sglyon saw your reply in another PR, thanks for explaining with long data, I will apply the comment to my PR too

2021-04-08 03:01 UTC, sglyon commented
Thank you for looking and responding here! 

Sorry I didn’t get a chance here. 

I have been extra tied up with external things this week. 

I’m working on some developer documentation that will hopefully make it easier to contribute. 

Thanks for your patience and willingness to help us.

2021-04-08 13:45 UTC, sglyon commented
The WIP docs for writing scrapers are here: https://github.com/covid-projections/can-scrapers/blob/docs/docs/scraping/writing_scrapers.rst

I'll attempt to get these "published" by EOD Friday

2021-04-09 13:05 UTC, sglyon commented
update -- scope of docs expanded a bit and it is now slated to be released by end of next week!

2021-04-13 01:39 UTC, mehanig commented
Hello, thank you for docs! 
They were helpfull. I pushed an update which creates dataframe in a format needed, I believe. 
Code is a bit repetetive, but let's focus on data format for now.

Since I am changing the existing file, I coudn't find a way to merge existing dataframe and demographic dataframe, is it better be a new file? Or there is an expected way to merge them?

Another question is that test is failing with `"NOT NULL constraint failed: covid_observations.location_id"`, What's needed to be done with location_id? I somehow missed this part, do I need to add location to variable files?

Thank you

2021-04-14 01:27 UTC, sglyon commented
Hey @mehanig thanks for the work here. 

> Since I am changing the existing file, I coudn't find a way to merge existing dataframe and demographic dataframe, is it better be a new file? Or there is an expected way to merge them? 

It's ok to have these scrapers live in the same file, but we won't need to worry about merging the data from the other scraper from the demographic data here. Let's keep them in two separate classes and let the database generate the combined dataset for us.

> Another question is that test is failing with "NOT NULL constraint failed: covid_observations.location_id", What's needed to be done with location_id? I somehow missed this part, do I need to add location to variable files?

You shouldn't have to add anything to the variable files. The general rule of thumb with the location Id is that your dataframe should have exactly one of the following:

1. A column named `location` containing county FIPS codes as integers AND you should set the class level property `has_location = True`
2. A column names `location_name` containing the name of a county as a string AND setting `has_location = False` at the root of the class

@tlyon3 will you please review  this PR on Wednesday morning and give any more guidance on the location_id issues 

(note I'm OOO for the next couple days, so @tlyon3  is helping pick up my slack!)

2021-04-15 14:14 UTC, tlyon3 requested changes
Looks good. Looks like got the `location_id` error fixed. Good job! Just one comment on code structure and this is good to go.

2021-04-15 14:14 UTC, tlyon3 commented on can_tools/scrapers/official/FL/fl_vaccine.py
> +    def normalize_group(self, df, demographic, dgroup, group_rename, cmu):
Looks like this method is unused? You normalize each demographic data in `if` blocks in the main `normalize` method. 

I'd recommend breaking them out into individual demographic normalize methods (eg `_normalize_sex`, `_normalize_age`, etc). Then call each one in the main `normalize ` method.

I believe that's what you were starting to do with this method.

2021-04-20 12:56 UTC, sglyon commented
Hi @mehanig just checking in to see if you've had any luck fixing the SQL issues with the location columns?

Would it help to have a brief call? If so, please reach out on slack

2021-05-24 22:26 UTC, sglyon commented
Hey @smcclure17 I have gone through this PR and made changes so that it now works!

Would you please review when you get a chance?

Thanks!

2021-05-24 23:44 UTC, smcclure17 approved these changes
tests passed and the data looks good/correct!

I don't have too much experience with parsing from PDFs, so no real comments there, but I think everything looks great!

2021-05-25 00:13 UTC, merged