Update South Dakota Vaccine Scraper
covid-projections/can-scrapers pull request #236
Opened 2021-04-14 05:14 UTC by smcclure17

Updates the SDVaccineCounty scraper to collect `total_vaccine_initiated`,`total_vaccine_completed`, and `total_vaccine_doses_administered`. 

I could not find a neat solution to #199, in that I still don't know why the request limits the number of responses to 12 or 13 counties. To circumvent this issue I broke up the fetch into 6 separate requests, returning data for 11 counties in each. Then I combined the results. If anyone knows of a fix/a more efficient way to approach this please let me know, but this should work correctly.

One question: If we collect manufacturer/dose specific data, do we want to collect/return that data? Or do we only care about the standard initiated/completed/administered?

2021-04-14 15:05 UTC, tlyon3 requested changes
If the manufacturer specific data (ex `moderna_vaccine_initiated/completed`) is available, I beleive we want that. That data is more granular and end users (or ourselves) can aggregate later down the line if wanted/needed.

2021-04-14 18:05 UTC, smcclure17 commented
great, thanks @tlyon3. 

Added trackers for each dose

2021-04-15 13:12 UTC, tlyon3 approved these changes

2021-04-19 14:42 UTC, sglyon commented
Great work!

2021-04-19 14:42 UTC, merged