updata DC vaccine demographics to match data
covid-projections/can-scrapers pull request #238
Opened 2021-04-15 20:06 UTC by smcclure17

This still needs a long-term fix for when DC changes the order of the data on their dashboard, but this updates it temporarily.

2021-04-16 13:48 UTC, tlyon3 approved these changes

2021-04-19 14:40 UTC, sglyon requested changes
Seems to be broken again... :(

The `Sex` scraper seems to be gathering data for race

The race scraper is broken

Age and ethnicity seem correct

2021-04-19 20:59 UTC, smcclure17 commented
This last commit should fix the ongoing headache these scrapers have been. Removes the individual demographic classes and creates `DCVaccineDemographics`. All demographic data is fetched at once using the `TableauScraper` module, and handled in one `normalize` function. This should eliminate the issue of the dashboard changing the ordering of the results.

2021-04-20 12:04 UTC, tlyon3 approved these changes

2021-04-20 12:46 UTC, sglyon approved these changes

2021-04-20 12:47 UTC, merged

2021-04-20 12:48 UTC, sglyon commented
Thank you for fixing this @smcclure17!