Created Connecticut Scraper
covid-projections/can-scrapers pull request #68
Opened 2021-01-04 06:05 UTC by blew2015

Created Connecticut scraper which pulls Covid data at the county and state wide levels.

2021-01-05 16:09 UTC, sglyon requested changes
Overall this is very good! Thank you @blew2015 

It looks like there are a lot of comments, but they are mostly 2 comments repeated once of each of the 3 scrapers.

2021-01-05 16:09 UTC, sglyon commented on can_tools/scrapers/official/CT/ct_state.py
> +    source = "https://data.ct.gov/resource/bfnu-rgqt.json"
Looks like `source` was set twice. I think this second one is correct

If so, let's delete the first one

2021-01-05 16:09 UTC, sglyon commented on can_tools/scrapers/official/CT/ct_state.py
> +        for c in [
This `for` loop isn't necessary.

When you call `cdh.melt` below and set `value_vars=crename.keys()`, pandas will ignore all columns that aren't in crename.keys() (or the id_vars)

2021-01-05 16:09 UTC, sglyon commented on can_tools/scrapers/official/CT/ct_state.py
> +        for c in [
This for loop can also be deleted (see above)

2021-01-05 16:09 UTC, sglyon commented on can_tools/scrapers/official/CT/ct_state.py
> +        tests_rename = {
It looks like you rename the columns here and then use the updated column names in `crename` below

Would it be possible to use the originanl column names as keys to `crename`? That save some typing!

2021-01-05 16:09 UTC, sglyon commented on can_tools/scrapers/official/CT/ct_state.py
> +        cdh_rename = {
See comment below about renaming columns AND using custom names as keys of `crename` later

2021-01-05 16:09 UTC, sglyon commented on can_tools/scrapers/official/CT/ct_state.py
> +        for c in [
Also not necessary

2021-01-06 11:02 UTC, sglyon requested changes
Hey @blew2015 thanks for making those changes.

A couple more and I think we are there

2021-01-06 11:02 UTC, sglyon commented on can_tools/scrapers/official/CT/ct_state.py
> +        for c in [c for c in tests_rename.values() if "number" in c]:
Same two comments here:

- Looks like the `.reindex` call is reduntant
- Loop iterator seems to be empty

2021-01-07 08:31 UTC, blew2015 commented on can_tools/scrapers/official/CT/ct_state.py
> +        for c in [
I messed up here.  I could have sworn I changed cdh_rename to  cdh.columns. Thats what I planned to do but apparently didn't. Should be fixed in the new commit. This has been pushed to after `cdh.melt` is called and is now called on that `value` column.

2021-01-11 15:32 UTC, sglyon commented on can_tools/scrapers/official/CT/ct_state.py
> +        for c in [
Excellent, thank you

2021-01-11 15:33 UTC, merged